# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: goal.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class CreateGoalResponseStatus(betterproto.Enum):
    OK = 0
    ALREADY_EXISTS = 1


@dataclass
class Goal(betterproto.Message):
    bank_account_id: int = betterproto.int32_field(1)
    created_at: str = betterproto.string_field(2)
    value: int = betterproto.int32_field(3)


@dataclass
class GetLastGoalRequest(betterproto.Message):
    bank_account_id: int = betterproto.int32_field(1)


@dataclass
class GoalResponse(betterproto.Message):
    goal: "Goal" = betterproto.message_field(1)


@dataclass
class CreateGoalRequest(betterproto.Message):
    bank_account_id: int = betterproto.int32_field(1)
    value: int = betterproto.int32_field(2)


@dataclass
class CreateGoalResponse(betterproto.Message):
    status: "CreateGoalResponseStatus" = betterproto.enum_field(1)
