# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: products/all.proto, products/count.proto, products/names.proto, products/consume.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class ConsumeProductResponseStatus(betterproto.Enum):
    OK = 0
    NOT_CONSUMABLE = 1
    ALREADY_CONSUMED = 2
    NOT_ENOUGH = 3


@dataclass
class ProductInfo(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    category: str = betterproto.string_field(3)
    level: int = betterproto.int32_field(4)


@dataclass
class ProductListResponse(betterproto.Message):
    products: List["ProductInfo"] = betterproto.message_field(1)


@dataclass
class ConsumableCategoriesResponse(betterproto.Message):
    consumables: List[str] = betterproto.string_field(1)


@dataclass
class ProductCountRequest(betterproto.Message):
    bank_account_id: int = betterproto.int64_field(1)
    product_name: str = betterproto.string_field(2)


@dataclass
class ProductCountResponse(betterproto.Message):
    count: int = betterproto.int64_field(1)


@dataclass
class ProductNamesRequest(betterproto.Message):
    bank_account_id: int = betterproto.int64_field(1)


@dataclass
class ProductNamesResponse(betterproto.Message):
    names: List[str] = betterproto.string_field(1)


@dataclass
class ConsumeProductRequest(betterproto.Message):
    product: str = betterproto.string_field(1)
    account: int = betterproto.int64_field(2)


@dataclass
class ConsumeProductResponse(betterproto.Message):
    status: "ConsumeProductResponseStatus" = betterproto.enum_field(1)
