# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: session/login.proto, session/user-info.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class LoginResponseLoginStatus(betterproto.Enum):
    OK = 0
    UNAUTHORIZED = 1
    ERROR = 2


@dataclass
class LoginRequest(betterproto.Message):
    login: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)


@dataclass
class LoginResponse(betterproto.Message):
    status: "LoginResponseLoginStatus" = betterproto.enum_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class UserInfo(betterproto.Message):
    name: str = betterproto.string_field(1)
    last_name: str = betterproto.string_field(2)
    patronymic: str = betterproto.string_field(3)
    login: str = betterproto.string_field(4)
    sex: str = betterproto.string_field(5)
    bonus: int = betterproto.int64_field(6)
    birthday: str = betterproto.string_field(7)
    bank_account_id: int = betterproto.int64_field(8)
    prefecture_name: str = betterproto.string_field(9)
    is_admin: bool = betterproto.bool_field(10)
