volumes:
  frontend_distribution:
  grafana_data:

services:
  webapp:
    build: .
    container_name: webapp
    volumes:
      - ./data/app_logs:/var/log:w
      - .:/hope-project:rw
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/metrics
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=somepasswd
      - POSTGRES_USER=hope
      - POSTGRES_DB=hope
      - PGDATA=/var/lib/pgsql/data
    volumes:
      - ./data/database_data:/var/lib/pgsql/data:rw
    ports:
      - 6000:5432
    restart: always
    healthcheck:
      test: pg_isready -U hope -d hope
      interval: 5s
      timeout: 5s
      retries: 10
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: sh -c "npm run build && tail -f /dev/null"
    volumes:
      - ./frontend:/frontend
      - frontend_distribution:/frontend/dist:rw
    restart: no

  nginx:
    image: nginx:mainline
    container_name: nginx
    volumes:
      - frontend_distribution:/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx-logs:/var/log:rw
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - webapp
      - frontend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - webapp

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
