services:
  webapp:
    build: .
    volumes:
      - logs:/var/log:w
    restart: always
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:16.3
    env_file:
      - path: .env
        required: false
    environment:
      - PGDATA=${SERVER_POSTGRES_DIRECTORY}/data
      - PGUSER=${POSTGRES_USER}
    volumes:
      - db-data:${SERVER_POSTGRES_DIRECTORY}/data:rw
    ports:
      - ${SERVER_POSTGRES_EXPOSED_PORT}:${SERVER_POSTGRES_PORT}
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
  reverse-proxy:
    image: nginx:mainline
    volumes:
      - ./app/static:/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log:rw
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - webapp


volumes:
  db-data:
    name: "database_data"
    driver: local
  logs:
    name: "server_logs"
    driver: local
  nginx-logs:
    name: "nginx_logs"
    driver: local