services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    networks:
      - local
    volumes:
      - logs:/var/log:w
    # we have hook for this
    stop_signal: SIGINT
    depends_on:
      database:
        condition: service_healthy
  database:
    env_file:
    - path: .env
      required: false
    environment:
      - PGDATA=${POSTGRESQL_DIRECTORY}/data
      - PGUSER=${POSTGRES_USER}
    image: "postgres:16.3"
    networks:
      - local
    volumes:
      - db-data:${POSTGRESQL_DIRECTORY}/data:rw
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  # network for all containers to talk to each other
  local:
    name: hope-internal-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/16
          ip_range: 172.1.1.0/24

volumes:
  db-data:
    driver: local
  logs:
    driver: local