services:
  webapp:
    build: .
    ports:
      - 5000:5000
    volumes:
      - logs:/var/log:w
    restart: always
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:16.3
    env_file:
    - path: .env
      required: false
    environment:
      - PGDATA=${SERVER_POSTGRES_DIRECTORY}/data
      - PGUSER=${POSTGRES_USER}
    volumes:
      - db-data:${SERVER_POSTGRES_DIRECTORY}/data:rw
    ports:
      ${SERVER_POSTGRES_EXPOSED_PORT}:${SERVER_POSTGRES_PORT}
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
  reverse-proxy:
    image: nginx:mainline
    # volumes:
    ports:
      - 80:80
      - 443:443


volumes:
  db-data:
    name: "database data"
    driver: local
  logs:
    name: "server logs"
    driver: local