services:
  webapp:
    build: .
    container_name: backend
    env_file:
      - path: .env
    volumes:
      - ./data/app_logs:/var/log:w
      - ./app:/hope-project/app:rw
    restart: always
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:16.3
    container_name: pg_db
    env_file:
      - path: .env
        required: false
    environment:
      - PGDATA=${SERVER_POSTGRES_DIRECTORY}/data
      - PGUSER=${POSTGRES_USER}
    volumes:
      - ./data/database_data:${SERVER_POSTGRES_DIRECTORY}/data:rw
    ports:
      - ${SERVER_POSTGRES_EXPOSED_PORT}:${SERVER_POSTGRES_PORT}
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 10
  reverse-proxy:
    image: nginx:mainline
    container_name: nginx
    volumes:
      - ./app/static:/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx-logs:/var/log:rw
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - webapp
