services:
  webapp:
    build: .
    container_name: webapp
    volumes:
      - ./data/app_logs:/var/log:w
      - .:/hope-project:rw
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=somepasswd
      - PGDATA=/var/lib/pgsql/data
      - PGUSER=hope
    volumes:
      - ./data/database_data:/var/lib/pgsql/data:rw
    ports:
      - 6000:5432
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 10
  nginx:
    image: nginx:mainline
    container_name: nginx
    volumes:
      - ./app/static:/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx-logs:/var/log:rw
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - webapp
