name: build and publish server
run-name: build and publish server ${{ gitverse.tag }}

on:
  push:
    branches:
      - master
    paths:
      - 'app/'
      - 'scripts/'
jobs:
  build:
    name: build docker image
    steps:
      - name: build
        env:
          - TAG: ${{ gitverse.tag }}
        # add cert here later
        run: docker build -f dockerfile -t hope-project:$TAG
      - name: tag built image
        env:
          - TAG: ${{ gitverse.tag }}
        run: docker tag hope-project:$TAG ashfungor/hope-project:latest
  publish:
    needs: build
    steps:
      - name: login to docker hub
        env:
          - SECRET: ${{ secrets.DOCKER_TOKEN }}
        run: echo $SECRET | docker -u ashfungor docker.io
      - name: push image
        run: docker image push --all-tags ashfungor/hope-project
